# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2d0bdc49a985cda04e0c04d986b1fa82b0ec9279029f9e8663a5584b1908fd14fbeda70f9564fe12ebea882a32536a50b5268e46b57eff7b4f65addc0a69a9c

test:
  secret_key_base: 31c5b28babdad2d277f39ecf79030cdaf204b3705fe87ed514eecbe784d245812b10471763d077ad170da6f9ae0d22c8d9946cf51ea5f75a9c4a232f7b94a995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
